#server
server:
  port: 8088
  servlet:
    context-path: /
  tomcat: 
    max-threads: 100
    
#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/tedu?useSSL=false&characterEncoding=utf8
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

#mybatis
mybatis-plus:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/**/*.xml
  
#logging
logging:
  level:
    cn.tedu: debug
    
